name: website CI Pipeline
on:
  push:
    branches:
       -main
jobs:
  build:

     runs-on: ubuntu-latest

     steps:

       - name: Checkout Code
         uses: actions/checkout@v3

       - name: Show Files
         run: ls

       - name: Check Html Files
         run: |
          echo "checking website files......"
          ls *.html

       -name: CI Success Message
        run: echo "website ci piepline running successfully"
